### ISSUE TITLE
Adding a new provider not possible

### ISSUE THREAD

**Issue by SlowMo24** [nilsnolde/orstools-qgis-plugin#103]
#### Here's what I did
Adding a new provider (ORS Tools -> Provider -> Settings-Wheel -> add -> specify name -> click ok) crashes with the following stacktrace:

```
Ein Fehler trat bei der Ausführung von Python-Code auf: 

NameError: name 'limit' is not defined 
Traceback (most recent call last):
  File "/home/moritz/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/gui/ORStoolsDialogConfig.py", line 96, in _add_provider
    self._add_box(provider_name, 'https://', '', new=True)
  File "/home/moritz/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/gui/ORStoolsDialogConfig.py", line 149, in _add_box
    limit=limit,
NameError: name 'limit' is not defined


Python-Version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS-Version: 3.4.7-Madeira Madeira, 5c56989 
```

---
#### Workaround
Manually editing the `config.yml`-file in the plugin direcotry (copy pasting the existing entry) should work fine.

**Comment by nilsnolde** [comment]
Thx for reporting, will be fixed this week too then!

**Comment by nilsnolde** [comment]
uploaded in plugin repo
