### ISSUE TITLE
Error ORS TOOLS

### ISSUE THREAD

**Issue by wilfriedkeolis** [nilsnolde/orstools-qgis-plugin#86]
An error has occurred while executing isochrones :

Paramètres en entrée:
{ 'INPUT_FIELD' : None, 'INPUT_METRIC' : 0, 'INPUT_POINT' : '5.0091718540903685,47.338208376506806 [EPSG:4326]', 'INPUT_POINT_LAYER' : None, 'INPUT_PROFILE' : 0, 'INPUT_PROVIDER' : 0, 'INPUT_RANGES' : '5', 'OUTPUT' : 'memory:' }

Traceback (most recent call last):
File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\requests\utils.py", line 940, in check_header_validity
if not pat.match(value):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:/Users/wrond/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\proc\isochrones_proc.py", line 245, in processAlgorithm
response = clnt.request(provider['endpoints'][self.ALGO_NAME], params)
File "C:/Users/wrond/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\core\client.py", line 152, in request
**final_requests_kwargs
File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\requests\sessions.py", line 525, in get
return self.request('GET', url, **kwargs)
File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\requests\sessions.py", line 498, in request
prep = self.prepare_request(req)
File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\requests\sessions.py", line 441, in prepare_request
hooks=merge_hooks(request.hooks, self.hooks),
File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\requests\models.py", line 310, in prepare
self.prepare_headers(headers)
File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\requests\models.py", line 444, in prepare_headers
check_header_validity(header)
File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\requests\utils.py", line 944, in check_header_validity
"bytes, not %s" % (name, value, type(value)))
requests.exceptions.InvalidHeader: Value for header {timeout: 60} must be of type str or bytes, not <class 'int'>

**Comment by nilsnolde** [comment]
Ha, interesting.. It's a quick fix though.

Which branch are you running? Looks like you already upgraded to `development` or is it `orstools`?

**Comment by wilfriedkeolis** [comment]
I would like to use the isochronous function 
It's orstools-qgis-plugin-development

**Comment by nilsnolde** [comment]
fixed in newest master and available in plugin repo

**Comment by wilfriedkeolis** [comment]
Thank you !
